### ISSUE TITLE
If the ram  size is less than 4096 machine word,then I CAN'T use mem malloc function,am'I right

### ISSUE THREAD

**Issue by Pupil2013** [EDI-Systems/M5P1_MuProkaron#6]
I saw the manual says mem pool can't less than 4096 machine word,
I use stm32l051,it's 32 bit mcu,then the ram must larger than 16kB to use the mem malloc functions.
Am I right?

**Comment by hungry-foolish** [comment]
yeah, you got it. You can’t use the built in allocator if you have too little memory. The dynamic memory allocation module provided is there to handle complex allocation requests (arbitrary block sizes) rather than simple fixed block size allocations. Designed as such, the dynamic memory module have a relatively higher memory overhead but is more flexible. If you have too little memory, then there’s no need for such a general-purpose dynamic memory allocation routine, you can supply your own routines which is usually just allocating a fixed block size, or do not use dynamic allocation at all. For devices with larger memory, if you just want very frequent fixed size block allocation/frees, you can use the built in allocator as a primary allocator, then allocate your smaller fixed size trunks with your own secondary allocator on the memory returned by it.

**Comment by hungry-foolish** [comment]
STM32L051 only have 8kB RAM. This is too small for an advanced general purpose memory allocation algorithm such as TLSF to make sense, thus It is rendered unusable.

**Comment by Pupil2013** [comment]
Thanks,Got it.
You art right ,there is no need to dynamic allocate memory in such small ram

**Comment by Pupil2013** [comment]
I think the task scheuler function is enough for my work,I will try this later

**Comment by hungry-foolish** [comment]
what project r u working on?

**Comment by Pupil2013** [comment]
Sensors powered by battery.
It's functions are simple ,but the logic is a little complex.
So I want a small rtos to schedule tasks, then I focus on something really matters.
